### ISSUE TITLE
crontab

### ISSUE THREAD

**Issue by MCTyler** [groenator/iptvboss-docker#1]
I don't understand your crontab run.....
![image](https://github.com/groenator/iptvboss-docker/assets/6390898/53869030-0bfc-42af-a849-c2ce79494c2d)

**Comment by groenator** [comment]
The image is building right now, once that's done pull the image and add the `SCHEDULE_CRON` environment variable with your own schedule. Please test it and let me know. More info in the readme.

**Comment by groenator** [comment]
The image is ready to be used.

**Comment by MCTyler** [comment]
If I add my own schedule, will it stay persistent?

**Comment by MCTyler** [comment]
0 */4 * * * This runs every 4 hours.

**Comment by groenator** [comment]
Yes, it's reading the schedule from your SCHEDULE_CRON environment.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by MCTyler** [comment]
Perfect! Every 4 hours...
![image](https://github.com/groenator/iptvboss-docker/assets/6390898/03243c03-3eab-4b70-9922-c8556a963237)
