### ISSUE TITLE
Portainer Error: Exited - crontab: your UID isn't in the passwd file. bailing out.

### ISSUE THREAD

**Issue by krhyatt11** [groenator/iptvboss-docker#18]
Error message within Portainer:
crontab: your UID isn't in the passwd file.
bailing out.
After latest (03-20) release, will no longer load the container image.

**Comment by groenator** [comment]
Please share the portainer configuration.

**Comment by krhyatt11** [comment]
If screenshots are ok - here they are...if you need something more specifc - let me know and how to do it...
![Portainer_3](https://github.com/groenator/iptvboss-docker/assets/109864715/9290b8d4-b5d3-4832-8278-afc38d938268)
![Portainer_2](https://github.com/groenator/iptvboss-docker/assets/109864715/41a85451-e267-45b3-b7c7-a97a16752a74)
![Portainer_1](https://github.com/groenator/iptvboss-docker/assets/109864715/06004dfa-125a-4656-9b18-4e53ee5a66d2)

**Comment by groenator** [comment]
Did you set some kind of user? Can you show me the actual docker-compose file?

**Comment by krhyatt11** [comment]
Just used the default from one of the original posts:
version: "2.1"
services:
  iptvboss:
    image: ghcr.io/groenator/iptvboss-docker:latest
    user: "1000:1000" # Set the user and group ID for the container.
    devices:
    - /dev/snd:/dev/snd # Required for audio support
    privileged: true # Required for audio support
    group_add:
      - audio # Required for audio support
    environment:
      TZ: "US/Eastern" #Set the timezone for the container.
      CRON_SCHEDULE: "0 0 * * *" #Set the cron schedule for the cron job that will update the EPG data.
 
    ports:
      - 8001:8001
      - 5901:5901
      - 6901:6901
    volumes:
    # Replace <local_volume> with the local directory where you want to store the IPTVBoss data. E.g., /home/user/iptvboss. Make sure the local folder has the correct permissions, otherwise IPTVBoss will not start.
      - /share:/shared
      - /share/Apps/iptvboss:/headless/IPTVBoss # Replace <local_volume> with the local directory where you want to store the IPTVBoss data. E.g., /home/user/iptvboss

**Comment by groenator** [comment]
Remove the line where says user: "1000:1000". You don't need it.

**Comment by groenator** [comment]
Check the docs for the latest version: https://github.com/groenator/iptvboss-docker?tab=readme-ov-file#docker-compose-preferred-way

**Comment by krhyatt11** [comment]
Ok
________________________________
