### ISSUE TITLE
Error code: 404 - When trying to access URL with password included

### ISSUE THREAD

**Issue by rh535** [groenator/iptvboss-docker#19]
Im getting an error when I include my password in the URL. Any idea on what I'm doing wrong?

My URL:
`http://myipandporthere/password=mypasswordhere`

Here is a screenshot of my variables - I'm running this through unRAID
![Screenshot 2024-03-21 1 29 24 PM](https://github.com/groenator/iptvboss-docker/assets/25569936/e42fda06-2893-4381-a078-98258f366212)

Here is a screenshot of the error:
![Screenshot 2024-03-21 1 30 42 PM](https://github.com/groenator/iptvboss-docker/assets/25569936/546a35cf-2df8-44ab-9236-22ca2627a61d)

**Comment by groenator** [comment]
Well, it appears you use a different password than what you have in your env. Can you remove the VNC_PASS variable, restart the container and then use the default pass? Default pass is: vncpassword

**Comment by groenator** [comment]
Follow these docs: https://github.com/groenator/iptvboss-docker?tab=readme-ov-file#accessing-the-vnc-server

**Comment by groenator** [comment]
So you can get in without a password but you can't get in with one set?
Can you see the logs of the container? What does it show? It should show logs.

**Comment by groenator** [comment]
I saw the logs of my container, and there's a typo in the read me. The actual url should be: http://<host-ip>:6901/?password=.

**Comment by groenator** [comment]
You have the wrong url, the url should be http://192.168.1.11:6901/?password=vncpassword

You are missing the question makr in front of password.

**Comment by groenator** [comment]
> > I saw the logs of my container, and there's a typo in the read me. The actual url should be: `http://<host-ip>:6901/?password=`
> > Please try it and let me know.
> 
> This fixed it! Thanks. Im still new and learning, but loving having this in docker.
> 
> Thanks for all your work

No worries, glad it worked out.
