### ISSUE TITLE
No Sound with IPTVBoss Player

### ISSUE THREAD

**Issue by MCTyler** [groenator/iptvboss-docker#2]
When I preview a stream I get no sound with the IPTVBoss Player (VLC)

**Comment by MCTyler** [comment]
Never connects to Pulse Audio....
![image](https://github.com/groenator/iptvboss-docker/assets/6390898/abe0682d-961e-4609-9ea1-1fb78e5de9ce)

**Comment by groenator** [comment]
I only tested to view the feed, and I never looked at the sound. Do me a favour. Can you test using a vnc client? Let me know if it is the same issue. If that's the case, I'll install the pulse audio codes.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by MCTyler** [comment]
I don't know anything about VNC.

**Comment by groenator** [comment]
Oh, ok. That looks I have to install pulse audio. I have to test it when I am home. I'll do it tonight.

**Comment by MCTyler** [comment]
Just simply `sudo apt install pulse audio`? What's the sudo password?

**Comment by groenator** [comment]
You can try installing this https://www.realvnc.com/en/connect/download/viewer/. The port 5901 works only via the vnc client, for browser you use 6901 port.

**Comment by MCTyler** [comment]
![image](https://github.com/groenator/iptvboss-docker/assets/6390898/5b2da261-698a-4883-884d-068194e66677)

**Comment by groenator** [comment]
Yeah, there's no such thing, lol. I am kidding. What I am trying to say is to install new packages, you have to rebuild the image. The docker container work differently than vm's.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by groenator** [comment]
Hi, 
To add audio I have to do something like this: https://github.com/ConSol/docker-headless-vnc-container/issues/77

I am still experimenting this feature. I will keep you posted.

**Comment by groenator** [comment]
Hi, 

I publish a new release with audio support: https://github.com/groenator/iptvboss-docker/releases/tag/v3.0

Please test it out and let me know. Follow the docs.

**Comment by groenator** [comment]
It appears if the audio group id mismatch between container and host it won't work. The container is using group id 29, your host needs to have the same id to work.

**Comment by groenator** [comment]
Currently, I don't have time to look at this issue. I made a few changes. However, due to different type of OS the changes don't work all the time as expected. I am going to be closing this issue. When I have time I will look at it again.
