### ISSUE TITLE
Proxmox LXC Container

### ISSUE THREAD

**Issue by TheJimmerJammer123** [groenator/iptvboss-docker#28]
Would be great to have a template to run boss in a lxc container on proxmox!

**Comment by groenator** [comment]
Hi, 

I am currently traveling, when I return back home, I will look at this.

**Comment by Daniel15** [comment]
You can create your own LXC container with your favourite Linux distro, install Docker in it, then run the IPTVBoss Docker container in there.

**Comment by groenator** [comment]
Closing this issue. I don't own a proxmox server. For now I am only supporting Docker.

**Comment by Daniel15** [comment]
@groenator You don't need Proxmox to use LXC. It's a standard Linux kernel feature and can be used on any Linux distro.

**Comment by groenator** [comment]
That is correct. Unfortunately, I don't have time and resource to develop the container for LXC. Like, I mentioned above. I am only supporting docker. 
You can try using LXC and generate your own template from docker-compose. Here's an example https://chatgpt.com/share/66e6102a-2bf0-8002-9f94-8861a4c0c184
