### ISSUE TITLE
Settings VNC_PASSWORDLESS to 'true' results in 'ERR_CONNECTION_REFUSED' 

### ISSUE THREAD

**Issue by GOvEy1nw** [groenator/iptvboss-docker#31]
Hi, this is a great container, thank you.

I've set it up on my Unraid server, and I wanted to use it without a password as I'm only accessing locally. However when I add 'VNC_PASSWORDLESS' with the value 'true' as a variable, it no longer works and results in 'ERR_CONNECTION_REFUSED' .

If I set it to 'false', it works fine.
If I set VNC_PW to be blank, and keep 'VNC_PASSWORDLESS' set to false, it also works fine (though still have to click the popup).
If I set VNC_PW to be blank, and set 'VNC_PASSWORDLESS' to true, it no longer works and results in 'ERR_CONNECTION_REFUSED' .

There's no errors in the docker log. The noVNC heading says 'Something went wrong, connection is closed'.

Is there a fix for this please?

**Comment by evans036a** [comment]
i have the same problem.

thanks,
steve

**Comment by groenator** [comment]
Hey guys, 
I've looked at the VNC base image documentation to try finding if there are issues with `VNC_PASSWORDLESS`. However, I haven't found any. I am going to try testing it this weekend in my home lab and get back to you. Unfortunately, this variable is set by the VNC base image not me.

**Comment by groenator** [comment]
Another way to access the container without click on the pop-up I use this URL: http://localhost:6901/?password=vncpassword. Replace localhost with your machine host IP.

**Comment by evans036a** [comment]
thanks a bunch for looking into this. i saw it was part of the base image
and not surprised the issue is upstream from your image.

for me its a minor irritant  that i can live with.

btw, i use a tight vnc client to access the container b/c it supports cut
and paste, the web client variant does not. so i cannot embed the pw to
avoid the pw prompt.

thanks again,
steve

**Comment by evans036a** [comment]
> This sucks that you cannot save the password on your vnc client. Have you tried using RealVNC client? If I remember correctly, you can save your password. What OS do you use?

windows for the front end. 

i used to use realVNC some years ago, but ran into issues that tightVNC solved. for the life of me i dont remember what those issues were. it may have been related to using it on a windows server (which i dont have any more). i'll give realVNC another try. 

thanks for the tip. 
steve.

**Comment by groenator** [comment]
It appears there's a bug on their side. When I use the debian version container and set the variable, the container doesn't start. If I use the Rocky base version and set the variable the container is starting well. I am going to open a case with them and see if there's anything to do to fix this. 

```
docker run -it -p 5901:5901 -p 6901:6901 -e VNC_PASSWORDLESS=true consol/rocky-xfce-vnc                       
Unable to find image 'consol/rocky-xfce-vnc:latest' locally
latest: Pulling from consol/rocky-xfce-vnc
489e1be6ce56: Already exists 
041b96c16345: Already exists 
267348571648: Already exists 
3d2a1ef7a37f: Already exists 
719040561794: Already exists 
956f0809b069: Already exists 
c66cf48d04ed: Already exists 
309b2626f099: Already exists 
0c244a6e87b0: Already exists 
620db9a9674d: Already exists 
152002d12272: Already exists 
4fe493324ae4: Already exists 
8a361259be9e: Already exists 
f03d5b5e1023: Already exists 
c8d90773a8f3: Already exists 
Digest: sha256:f69f5caa1c9d3777704cc18c319fac257f6ae34a22bee802f9f433636d5b932c
Status: Downloaded newer image for consol/rocky-xfce-vnc:latest
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
USER_ID: 1000, GROUP_ID: 0
nss_wrapper location: /usr/lib64/libnss_wrapper.so
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

------------------ update chromium-browser.init ------------------

... set window size 1280 x 1024 as chrome window size!


------------------ change VNC password  ------------------

------------------ start noVNC  ----------------------------
start vncserver with param: VNC_COL_DEPTH=24, VNC_RESOLUTION=1280x1024
...
start window manager
...


------------------ VNC environment started ------------------

VNCSERVER started on DISPLAY= :1 
        => connect via VNC viewer with 172.17.0.2:5901

noVNC HTML client started:
        => connect via http://172.17.0.2:6901/?password=...

```

**Comment by groenator** [comment]
PR raised: https://github.com/ConSol/docker-headless-vnc-container/issues/205

**Comment by evans036a** [comment]
> Issue raised: [ConSol/docker-headless-vnc-container#205](https://github.com/ConSol/docker-headless-vnc-container/issues/205)

thankyou

**Comment by groenator** [comment]
You are welcome!

**Comment by evans036a** [comment]
again, your efforts are greatly appreciated. many thanks.

**Comment by groenator** [comment]
Issue fixed https://github.com/groenator/iptvboss-docker/pull/36. Pull the latest version and test it. It works fine on my end. Re-open the issue if you are still encountering issues.

**Comment by evans036a** [comment]
tested and working as expected.

many thanks,
steve
