### ISSUE TITLE
dbrestore java error from cloud

### ISSUE THREAD

**Issue by Cylac** [groenator/iptvboss-docker#42]
Hi, I'm trying to restore my database from my cloud link and I'm getting these errors:

![iptvboss-dbrestore-cloud-error](https://github.com/user-attachments/assets/1e7c9ebf-1047-4b03-86a0-cfb08eea4e9c)

I was even trying to do a local restore and I kept on getting similar errors too.

This is from a fresh install from a few days ago.

My database works fine when I load it on Windows.

Thanks

**Comment by groenator** [comment]
Hi 

Please raise this issue with the develope in their discord. I only support issues related to the docker image.

Regards,

**Comment by Cylac** [comment]
> Hi
> 
> Please raise this issue with the develope in their discord. I only support issues related to the docker image.
> 
> Regards,

sounds good thanks! wasn't sure since I'm only getting this error while using iptvboss in the VNC environment.

**Comment by Cylac** [comment]
I've brought this issue up with some of the dev people on discord and they don't seem to know what's going on either. I'll keep on trying to figure out somehow.

**Comment by Cylac** [comment]
omg I just figured out WHY I was having all these probs.. my volumes setting in my docker-compose file was wrong so it was never mounting my /home/user/iptvboss info and probably why it couldn't write certain information! My bad!
(Still familiarizing myself with docker and iptvboss)

**Comment by groenator** [comment]
I am glad it worked out.
