### ISSUE TITLE
[Feature Request] ARM support

### ISSUE THREAD

**Issue by LJAM96** [groenator/iptvboss-docker#7]
`iptvboss Pulling no matching manifest for linux/arm64/v8 in the manifest list entries`

IPTVBoss supports ARM but on attempting to pull on my machine it appears the docker image doesnt.

Thanks

**Comment by groenator** [comment]
I need to build a new image with ARM, the base image is on x86. I will have to check if VNC has ARM support already.

**Comment by groenator** [comment]
Based on the VNC image they only support the following:
Current provided OS & UI sessions:

    consol/rocky-xfce-vnc: Rocky 9 with Xfce4 UI session
    consol/debian-xfce-vnc: Debian 11 with Xfce4 UI session
    consol/rocky-icewm-vnc: Rocky 9 with IceWM UI session
    consol/debian-icewm-vnc: Debian 11 with IceWM UI session

I am using this as base image: https://github.com/ConSol/docker-headless-vnc-container

**Comment by LJAM96** [comment]
ah I understand, I wasnt sure it was just a case of updating the manifest.

On the docker hub it appears all of `consol/rocky-xfce-vnc, consol/debian-xfce-vnc, consol/rocky-icewm-vnc, consol/debian-icewm-vnc` do have support which is good

**Comment by groenator** [comment]
Do they have support? if they do, then is weird why is not working. 
we use this image. when you start the container, can you check to see what version of iptvboss is installing? I wonder if is picking up the x86 instead

**Comment by LJAM96** [comment]
Yeh fully supported, Ive deployed a `consol/debian-xfce-vnc` instance.
Installed IPTVBoss 3.4.160.0 and it functions fine.

Although I couldnt install with the commands on the IPTVBoss website due to 
`root@0996c8ac977f:/headless# CPU=$(dpkg-architecture -q DEB_HOST_ARCH_CPU)
bash: dpkg-architecture: command not found
`

So I pulled the ARM deb and installed

**Comment by groenator** [comment]
It should find the cli, I wonder if the package is not available in arm. What I can do is change the way iptvboss is installing and not use this command, use something else which can work on both sides. I will let you know when I'll start working on it.

**Comment by groenator** [comment]
I just remember the pipeline is configured to build the images automatically, and it's using x86.

**Comment by redwildcat** [comment]
Were you able to investigate this? I'm on an M2 Mac and get the same error is OP.

**Comment by groenator** [comment]
Hey, 

I am going to look at it over the weekend. 

Regards,

**Comment by groenator** [comment]
Hi,

Sorry it took a while, I published a new docker with with arm support: 

This is the image url: docker pull ghcr.io/groenator/iptvboss-docker:latest-arm 

Please try it out and let me know. 

Regards,

**Comment by redwildcat** [comment]
The download for arm (on M2 Mac) worked like a charm.  Thank you for all your hard work on this!

**Comment by groenator** [comment]
I am glad it worked well. I am going to close this feature request.
